### PR TITLE
Client will make request for all photos;

### PR DESCRIPTION
**Pull request by jase-d**
Messed up with previous pull request by adding in previous push will be looking into making separate branches for everything

Item 1:
Sets up webpack/babel to work with client/server
Creates index.html && index.jsx for basic browser structure

Item2:
Gathers in store.jsx
forms quick template of one listing
log the info and photos of first listing in db

Item3:
Adds Info react component with basic template

Item4:
Refactors server http handlers to send back one unique listing per endpoint,
which is now /mosaic/0 - /mosaic/99

Item5:
Refactor seeding script to properly function;
Crudely renders listing info and its first 5 photos

Item6:
Creates basic template for the service;
Adds design and some user interaction when hovering pictures
[link to gif](http://g.recordit.co/YC8BwovkeA.gif)

@bland0 
@javsflores

### CODE REVIEW

**Review by javsflores — COMMENTED** [review]
Axios request are looking good. Is the console.log(info, photos) line intended to be removed or will it serve a purpose later on?

**Review by javsflores — COMMENTED** [review]
Reviewing: Add Info react element; Very basic just text

Looks good.

**Review by javsflores — COMMENTED** [review]
Reviewing: quick

looks like you just added the locationID and made the appropriate changes to your seed class. Looks good to me.

**Review by javsflores — COMMENTED** [review]
Reviewing: Update script to seed db

- change to buildDB script looks good.
- all other changes make since and are simple enough to follow.

**Review by javsflores — COMMENTED** [review]
Reviewing: Refactor server http handler to send back a particular listing for every

- first change to getInfo function looks good.
- similar change to getListing. Looks good.

**Review by javsflores — COMMENTED** [review]
Reviewing: Reorganizing seeding function; Renders random listing

- I could be wrong, but I'm not sure you need the "return" inside your componentDidMount function, but even if you don't need it, I'm not sure if there's anything wrong with having it there... so this is more of an observation. Other than that, your AppPhotos structure is looking nice.

- for your Info component, why did you use multiple spans instead of using one and utilizing spacing? (just curious) to clarify what I mean: <span>{info.rating} {info.superhost} {info.location}</span>

-MosaicSmall looks good, beside the console.log(firstPhotos) which I assume will be taken out later on.

**Review by javsflores — COMMENTED** [review]
Reviewing: Refactor Back End testing to updated changes

- for you console.log('ERROR GETTING'), i'm thinking it would also be good to say something like, console.log('ERROR: ' + err)? In case someone else later works on your code and wants to know what the exact error reads?

- NICE!!! You started writing tests!

**Review by javsflores — COMMENTED** [review]
Reviewing: Create frame for photos

- the CSS looks fine.
- the changes to your components also look good.
- added devDependencies look good too.
- the tests also look fine to me, but I haven't gotten too much practice writing tests myself, so if you need an additional pair of eyes on those, feel free to ask Branan.

**Review by javsflores — COMMENTED** [review]
Reviewing: Create basic layout with first layer of css

- Looks good!

**Review by javsflores — COMMENTED** [review]
Reviewing: Quick update on sizing; Delete borders

- CSS looks good.

**Review by javsflores — COMMENTED** [review]
Reviewing: Touch up for exact sizing on photos; Removes border from photos

- Changes look good!

**Review by javsflores — APPROVED** [review]
Hey @jase-d,

Just reviewed all your commits. I made individual comments as I was going through your work. Keep up the great work! 👍

- Javier

**Comment by jase-d** [comment]
Thanks for the awesome feedback @javsflores 

---------------------------------------------------------------------------------------------------------------------------
Replying to: 
"for your Info component, why did you use multiple spans instead of using one and utilizing spacing? (just curious) to clarify what I mean: {info.rating} {info.superhost} {info.location}"
AND 
"-MosaicSmall looks good, beside the console.log(firstPhotos) which I assume will be taken out later on."
---------------------------------------------------------------------------------------------------------------------------
-I ended up using spans because as of right now these are just placeholders. Eventually I plan to have them all share the same class but also have separate id's. That way I can add in a star image on the ratings etc..
Also, the span tag keeps everything easily in a row and keeps spacing.

-The console.log's I use will stay for a while through the development stage. I use them as mini tests throughout, however I will keep them to a minimum with other people viewing my code.

**Pull request merged**
